### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by EricPuskas** [cyps1000/prime-gaming#14]
Implement a navbar

- [x]  Implement a mockup navbar using the [material-ui AppBar](https://material-ui.com/components/app-bar/) as base.
- [x] Establish the design
- [x] Menu items

- will update with more info.

**Comment by cyps1000** [comment]
- [ ] Navbar will be same color #0d1117; dark or light theme
- [ ] Will be sticky
- [ ] to add routes
- [ ] dropdown menu for ro and eng #28 
- [ ] right side of the navbar: Login #20 and Signup #21. 
- [ ] Search feature #26
